bootstrap Ubuntu instance, install and configure Neo4j

diff --git a/gfe-db/database/template.yaml b/gfe-db/database/template.yaml
--- a/gfe-db/database/template.yaml
+++ b/gfe-db/database/template.yaml
@@ -89,8 +89,7 @@ Resources:
       IamInstanceProfile: !Ref Neo4jDatabaseInstanceProfile
       Monitoring: true
       BlockDeviceMappings:
-        # - DeviceName: /dev/sda1
-        - DeviceName: /dev/xvda
+        - DeviceName: /dev/sda1
           Ebs:
             VolumeSize: !Ref DatabaseVolumeSize
             VolumeType: gp3
@@ -134,7 +133,7 @@ Resources:
           /usr/bin/java -version
           export UBUNTU_HOME=/home/ubuntu
           export INSTANCE_ID=$(curl -sS http://169.254.169.254/latest/meta-data/instance-id)
-          export NEO4J_HOME=/opt/bitnami/neo4j
+          export NEO4J_HOME=/var/lib/neo4j
           mkdir -p /tmp/logs/system /tmp/logs/neo4j
           # copy_logs_to_s3() {
           #   # copy logs to S3
@@ -176,7 +175,7 @@ Resources:
           echo "INSTANCE_ID=$INSTANCE_ID" > $UBUNTU_HOME/env.sh
           echo "UBUNTU_HOME=$UBUNTU_HOME" >> $UBUNTU_HOME/env.sh
           echo "NEO4J_HOME=$NEO4J_HOME" >> $UBUNTU_HOME/env.sh
-          echo "BITNAMI_NEO4J=/bitnami/neo4j" >> $UBUNTU_HOME/env.sh
+          # echo "BITNAMI_NEO4J=/bitnami/neo4j" >> $UBUNTU_HOME/env.sh
           echo "STAGE=${Stage}" >> $UBUNTU_HOME/env.sh
           echo "APP_NAME=${AppName}" >> $UBUNTU_HOME/env.sh
           echo "USE_PRIVATE_SUBNET=${usePrivateSubnet}" >> $UBUNTU_HOME/env.sh
@@ -206,9 +205,68 @@ Resources:
           #     fi
           # done
           # [ $exit_code -eq 0 ] && echo "INFO: Environment variables set" || (echo $msg && cfn_signal 1 "$msg" && exit 1)
+          install_neo4j() {
+            echo "INFO: Installing Neo4j"
+            wget -O - https://debian.neo4j.com/neotechnology.gpg.key | sudo apt-key add -
+            echo 'deb https://debian.neo4j.com stable 5' | tee -a /etc/apt/sources.list.d/neo4j.list
+            apt-get update -y
+            apt list -a neo4j
+            add-apt-repository -y universe
+            apt-get install -y neo4j=1:5.14.0
+            systemctl enable neo4j
+
+            # TODO add dynamic password generation
+            neo4j-admin dbms set-initial-password gfedb2023
+          }
+          install_apoc_plugin() {
+            echo "INFO: Installing APOC"
+            mv /var/lib/neo4j/labs/apoc-*-core.jar /var/lib/neo4j/plugins
+          }
+          build_neo4j_public_config() {
+            echo "INFO: Building Neo4j public config"
+
+            # TODO fix missing env vars
+            # check that SUBDOMAIN and HOST_DOMAIN are set
+            if [ -z "$SUBDOMAIN" ] || [ -z "$HOST_DOMAIN" ]; then
+              echo "ERROR: SUBDOMAIN and HOST_DOMAIN must be set"
+              exit 1
+            fi
+
+            cp /etc/neo4j/neo4j.conf /etc/neo4j/neo4j.conf.bak
+            sed -i 's/#server.default_listen_address=0.0.0.0/server.default_listen_address=0.0.0.0/g' /etc/neo4j/neo4j.conf
+            sed -i "s/#server.default_advertised_address=localhost/server.default_advertised_address=$SUBDOMAIN.$HOST_DOMAIN/g" /etc/neo4j/neo4j.conf
+            sed -i 's/#server.bolt.tls_level=DISABLED/server.bolt.tls_level=REQUIRED/g' /etc/neo4j/neo4j.conf
+            sed -i 's/#server.bolt.listen_address=:7687/server.bolt.listen_address=:7687/g' /etc/neo4j/neo4j.conf
+            sed -i 's/#server.bolt.advertised_address=:7687/server.bolt.advertised_address=:7687/g' /etc/neo4j/neo4j.conf
+            sed -i 's/server.http.enabled=true/#server.http.enabled=true/g' /etc/neo4j/neo4j.conf
+            sed -i 's/server.https.enabled=false/server.https.enabled=true/g' /etc/neo4j/neo4j.conf
+            sed -i 's/#server.https.listen_address=:7473/server.https.listen_address=:7473/g' /etc/neo4j/neo4j.conf
+            sed -i 's/#server.https.advertised_address=:7473/server.https.advertised_address=:7473/g' /etc/neo4j/neo4j.conf
+            sed -i 's/#dbms.ssl.policy.bolt.enabled=true/dbms.ssl.policy.bolt.enabled=true/g' /etc/neo4j/neo4j.conf
+            sed -i 's/#dbms.ssl.policy.bolt.base_directory=certificates\/bolt/dbms.ssl.policy.bolt.base_directory=\/var\/lib\/neo4j\/certificates\/bolt/g' /etc/neo4j/neo4j.conf
+            sed -i 's/#dbms.ssl.policy.bolt.private_key=private.key/dbms.ssl.policy.bolt.private_key=\/var\/lib\/neo4j\/certificates\/bolt\/neo4j.key/g' /etc/neo4j/neo4j.conf
+            sed -i 's/#dbms.ssl.policy.bolt.public_certificate=public.crt/dbms.ssl.policy.bolt.public_certificate=\/var\/lib\/neo4j\/certificates\/bolt\/neo4j.cert/g' /etc/neo4j/neo4j.conf
+            sed -i 's/#dbms.ssl.policy.bolt.client_auth=NONE/dbms.ssl.policy.bolt.client_auth=NONE/g' /etc/neo4j/neo4j.conf
+            sed -i 's/#dbms.ssl.policy.https.enabled=true/dbms.ssl.policy.https.enabled=true/g' /etc/neo4j/neo4j.conf
+            sed -i 's/#dbms.ssl.policy.https.base_directory=certificates\/https/dbms.ssl.policy.https.base_directory=\/var\/lib\/neo4j\/certificates\/https/g' /etc/neo4j/neo4j.conf
+            sed -i 's/#dbms.ssl.policy.https.private_key=private.key/dbms.ssl.policy.https.private_key=\/var\/lib\/neo4j\/certificates\/https\/neo4j.key/g' /etc/neo4j/neo4j.conf
+            sed -i 's/#dbms.ssl.policy.https.public_certificate=public.crt/dbms.ssl.policy.https.public_certificate=\/var\/lib\/neo4j\/certificates\/https\/neo4j.cert/g' /etc/neo4j/neo4j.conf
+            sed -i 's/#dbms.ssl.policy.https.client_auth=NONE/dbms.ssl.policy.https.client_auth=NONE/g' /etc/neo4j/neo4j.conf
+            sed -i 's/#dbms.logs.http.enabled=true/dbms.logs.http.enabled=true/g' /etc/neo4j/neo4j.conf
+            sed -i 's/#dbms.security.allow_csv_import_from_file_urls=true/dbms.security.allow_csv_import_from_file_urls=true/g' /etc/neo4j/neo4j.conf
+            sed -i 's/#dbms.security.procedures.unrestricted=my.extensions.example,my.procedures.*/dbms.security.procedures.unrestricted=apoc.*,gds.*/g' /etc/neo4j/neo4j.conf
+            sed -i 's/#dbms.security.procedures.allowlist=apoc.coll.*,apoc.load.*,gds.*/dbms.security.procedures.allowlist=apoc.*,gds.*/g' /etc/neo4j/neo4j.conf
+            neo4j-admin server memory-recommendation | grep -v ^# >> /etc/neo4j/neo4j.conf
+          }
           echo "INFO: Downloading scripts"
           aws s3 cp --quiet --recursive s3://${DataBucketName}/config/scripts/ $UBUNTU_HOME/
-          # echo "INFO: Initiliazing Neo4j database"
+          echo "INFO: Initiliazing Neo4j database"
+          install_neo4j
+          install_apoc_plugin
+          build_neo4j_public_config
+          echo "Current dir: $(pwd)"
+          cd $UBUNTU_HOME && make bootstrap
+          systemctl start neo4j
           # # TODO add cfn-signal handling to Makefile
           # cd $UBUNTU_HOME && make neo4j
           # exit_code=$?
@@ -221,8 +279,8 @@ Resources:
           # echo "INFO: Found Cypher constraints: $cypher_constraints" | tr '\n' ' ' | sed 's/  / /g' || (msg="ERROR: No Cypher constraints were found" && echo $msg && cfn_signal 1 "$msg" && exit 1)
           # mkdir logs
           # sudo journalctl -b > logs/boot.log
-          # cat /opt/bitnami/neo4j/logs/neo4j.log > logs/neo4j.log
-          # cat /opt/bitnami/neo4j/logs/debug.log > logs/debug.log
+          # cat /var/lib/neo4j/logs/neo4j.log > logs/neo4j.log
+          # cat /var/lib/neo4j/logs/debug.log > logs/debug.log
           # cfn_signal 0 "INFO: Finished running user data for ${AWS::StackName}-database instance"
       Tags:
         - Key: Name
@@ -358,7 +416,7 @@ Resources:
           workingDirectory:
             type: String
             description: Working directory
-            default: /home/bitnami
+            default: /home/ubuntu
         mainSteps:
           - action: aws:runShellScript
             name: runShellScript
@@ -441,7 +499,7 @@ Resources:
           workingDirectory:
             type: "String"
             description: "Working directory"
-            default: "/home/bitnami"
+            default: "/home/ubuntu"
           executionTimeout:
             type: "String"
             description: "(Optional) The time in seconds for a command to complete before it is considered to have failed. Default is 3600 (1 hour). Maximum is 28800 (8 hours)."
