configure cloudwatch agent and cfn signal in user data

diff --git a/gfe-db/database/template.yaml b/gfe-db/database/template.yaml
--- a/gfe-db/database/template.yaml
+++ b/gfe-db/database/template.yaml
@@ -60,6 +60,9 @@ Resources:
   
   Neo4jDatabaseInstance:
     Type: AWS::EC2::Instance
+    CreationPolicy:
+      ResourceSignal:
+        Timeout: PT5M
     Properties:
       KeyName: !Sub '{{resolve:ssm:/${AppName}/${Stage}/${AWS::Region}/EC2KeyPairName}}'
       DisableApiTermination: false
@@ -92,47 +95,67 @@ Resources:
             curl \
             software-properties-common \
             zip \
-            unzip
-          curl -o /root/amazon-cloudwatch-agent.deb https://s3.amazonaws.com/amazoncloudwatch-agent/debian/amd64/latest/amazon-cloudwatch-agent.deb
-          dpkg -i -E /root/amazon-cloudwatch-agent.deb
+            unzip \
+            collectd \
+            python3-setuptools
+          mkdir -p /tmp/ssm /tmp/amazon-cloudwatch-agent /tmp/cfn /tmp/logs
+          # Install CloudFormation helper scripts (for cfn-signal)
+          wget -q -O /tmp/cfn/aws-cfn-bootstrap-py3-latest.tar.gz https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-py3-latest.tar.gz
+          python3 -m easy_install --script-dir /opt/aws/bin /tmp/cfn/aws-cfn-bootstrap-py3-latest.tar.gz
+          # Install SSM Agent for automation
+          wget -q -O /tmp/ssm/amazon-ssm-agent.deb https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/debian_amd64/amazon-ssm-agent.deb
+          sudo dpkg -i /tmp/ssm/amazon-ssm-agent.deb
+          sudo systemctl enable amazon-ssm-agent
+          # Install and configure CloudWatch Agent for logs and metrics
+          wget -q -O /tmp/amazon-cloudwatch-agent/amazon-cloudwatch-agent.deb https://s3.amazonaws.com/amazoncloudwatch-agent/debian/amd64/latest/amazon-cloudwatch-agent.deb
+          dpkg -i -E /tmp/amazon-cloudwatch-agent/amazon-cloudwatch-agent.deb
           aws s3 cp s3://${DataBucketName}/config/amazon-cloudwatch-agent/amazon-cloudwatch-agent.json /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
           systemctl enable amazon-cloudwatch-agent.service
           service amazon-cloudwatch-agent start
-          echo "Downloading Neo4j configuration from ${DataBucketName} to /etc/neo4j/neo4j.template..."
-          aws s3 cp s3://${DataBucketName}/config/neo4j/neo4j.template /etc/neo4j/neo4j.template
-          echo "Downloading APOC Full plugin..."
-          curl -L https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.4.0.3/apoc-4.4.0.3-all.jar -O
-          mv apoc-4.4.0.3-all.jar /var/lib/neo4j/plugins/apoc-4.4.0.3-all.jar
-          echo "Downloading Neo4j Graph Data Science plugin..."
-          curl -L https://graphdatascience.ninja/neo4j-graph-data-science-2.0.1.zip -O
-          unzip neo4j-graph-data-science-2.0.1.zip
-          mv neo4j-graph-data-science-2.0.1.jar /var/lib/neo4j/plugins/neo4j-graph-data-science-2.0.1.jar
-          echo "Resetting default password..."
-          neo4j-admin set-initial-password ${Neo4jPassword}
-          echo "Starting Neo4j server..."
-          systemctl enable neo4j.service
-          systemctl start neo4j
+          # # Configure Neo4j server
+          # echo "Downloading Neo4j configuration from ${DataBucketName} to /etc/neo4j/neo4j.template..."
+          # aws s3 cp s3://${DataBucketName}/config/neo4j/neo4j.template /etc/neo4j/neo4j.template
+          # echo "Downloading APOC Full plugin..."
+          # curl -L https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.4.0.3/apoc-4.4.0.3-all.jar -O
+          # mv apoc-4.4.0.3-all.jar /var/lib/neo4j/plugins/apoc-4.4.0.3-all.jar
+          # echo "Downloading Neo4j Graph Data Science plugin..."
+          # curl -L https://graphdatascience.ninja/neo4j-graph-data-science-2.0.1.zip -O
+          # unzip neo4j-graph-data-science-2.0.1.zip
+          # mv neo4j-graph-data-science-2.0.1.jar /var/lib/neo4j/plugins/neo4j-graph-data-science-2.0.1.jar
+          # echo "Resetting default password..."
+          # Stop Neo4j & Reset password
+          # /opt/bitnami/ctlscript.sh stop neo4j
+          # /opt/bitnami/neo4j/bin/neo4j-admin set-initial-password ${Neo4jPassword}
+          # echo "Restarting Neo4j server..."
+          # sudo /opt/bitnami/ctlscript.sh start neo4j
+          # systemctl enable neo4j.service
+          # systemctl start neo4j
           until $(curl --output /dev/null --silent --head --fail http://localhost:7474) ; do \
-            printf '.' ; \
-            sleep 1 ; \
+          printf '.' ; \
+          sleep 1 ; \
           done
           printf "%s\n" " "
           echo "Neo4j is ready"
-          mkdir -p /var/lib/neo4j/backups /var/lib/neo4j/cypher
-          echo "Fetching cypher scripts from S3..."
-          aws s3 cp --recursive s3://${DataBucketName}/config/neo4j/cypher/ /var/lib/neo4j/cypher/
-          cat /var/lib/neo4j/cypher/${Neo4jInitScript} | \
-            /usr/bin/cypher-shell \
-              -u neo4j \
-              -p ${Neo4jPassword}
+          # mkdir -p /var/lib/neo4j/backups /var/lib/neo4j/cypher
+          # echo "Fetching cypher scripts from S3..."
+          # aws s3 cp --recursive s3://${DataBucketName}/config/neo4j/cypher/ /var/lib/neo4j/cypher/
+          # cat /var/lib/neo4j/cypher/${Neo4jInitScript} | \
+          # /usr/bin/cypher-shell \
+          #   -u neo4j \
+          #   -p ${Neo4jPassword}
           echo "Copying logs to S3..."
-          mkdir -p /tmp/logs
           export INSTANCE_ID=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/meta-data/instance-id)
           journalctl -b > /tmp/logs/$INSTANCE_ID-boot.log
           echo "Copying Neo4j logs to S3..."
           journalctl -e -u neo4j > /tmp/logs/neo4j.log
           aws s3 cp --recursive /tmp/logs/ s3://${DataBucketName}/logs/database/bootstrap/$(date +'%Y/%m/%d/%H')/
-          echo "Ready"
+          # Signal the status from cfn-init; Ideally the UserData is run using cfn-init, and the exit code of cfn-init is passed to cfn-signal indicating
+          # successful deployment
+          /opt/aws/bin/cfn-signal \
+            --exit-code $? \
+            --stack  ${AWS::StackName} \
+            --resource Neo4jDatabaseInstance \
+            --region  ${AWS::Region}
       Tags:
         - Key: Name
           Value: !Ref AppName
