fix cypher-shell path in load script and run final validation in user data script

diff --git a/gfe-db/database/template.yaml b/gfe-db/database/template.yaml
--- a/gfe-db/database/template.yaml
+++ b/gfe-db/database/template.yaml
@@ -309,26 +309,24 @@ Resources:
           install_neo4j
           echo "INFO: Downloading scripts"
           aws s3 cp --quiet --recursive s3://${!DATA_BUCKET_NAME}/config/scripts/ $EC2_USER_HOME/
-
-          # TODO update initialization scripts
           cd $EC2_USER_HOME && make neo4j
-          # CREATE_NEO4J_USERS=${CreateNeo4jUsers}
-          # if [ ! -z "$CREATE_NEO4J_USERS" ]; then
-          #   echo "INFO: Creating Neo4j users"
-          #   cd $EC2_USER_HOME && make neo4j.query.create-users users="${CreateNeo4jUsers}"
-          # else 
-          #   echo "INFO: No Neo4j users to create"
-          # fi
-          # unset CREATE_NEO4J_USERS
-          # exit_code=$?
-          # [ $exit_code -eq 0 ] && echo "INFO: Neo4j initialized successfully" || (msg="ERROR: Neo4j failed to initialize" && echo $msg && cfn_signal 1 "$msg" && exit 1)
-          # cypher_constraints=$(sudo make neo4j.query.show-constraints | awk -F, 'NR>1 {print $2}')
-          # [[ $(echo "$cypher_constraints" | grep -c "gfe_constraint") -gt 0 && \
-          #   $(echo "$cypher_constraints" | grep -c "ipd_acc_constraint") -gt 0 && \
-          #   $(echo "$cypher_constraints" | grep -c "ipd_allele_constraint") -gt 0 \
-          #   && $(echo "$cypher_constraints" | grep -c "submitter_constraint") -gt 0 ]] && \
-          # echo "INFO: Found Cypher constraints: $cypher_constraints" | tr '\n' ' ' | sed 's/  / /g' || (msg="ERROR: No Cypher constraints were found" && echo $msg && cfn_signal 1 "$msg" && exit 1)
-          # cfn_signal $exit_code "INFO: Finished running user data for ${AWS::StackName}-database instance"
+          CREATE_NEO4J_USERS=${CreateNeo4jUsers}
+          if [ ! -z "$CREATE_NEO4J_USERS" ]; then
+            echo "INFO: Creating Neo4j users"
+            cd $EC2_USER_HOME && make neo4j.query.create-users users="${CreateNeo4jUsers}"
+          else 
+            echo "INFO: No Neo4j users to create"
+          fi
+          unset CREATE_NEO4J_USERS
+          exit_code=$?
+          [ $exit_code -eq 0 ] && echo "INFO: Neo4j initialized successfully" || (msg="ERROR: Neo4j failed to initialize" && echo $msg && cfn_signal 1 "$msg" && exit 1)
+          cypher_constraints=$(make neo4j.query.show-constraints | awk -F, 'NR>1 {print $2}')
+          [[ $(echo "$cypher_constraints" | grep -c "gfe_constraint") -gt 0 && \
+            $(echo "$cypher_constraints" | grep -c "ipd_acc_constraint") -gt 0 && \
+            $(echo "$cypher_constraints" | grep -c "ipd_allele_constraint") -gt 0 \
+            && $(echo "$cypher_constraints" | grep -c "submitter_constraint") -gt 0 ]] && \
+          echo "INFO: Found Cypher constraints: $cypher_constraints" | tr '\n' ' ' | sed 's/  / /g' || (msg="ERROR: No Cypher constraints were found" && echo $msg && cfn_signal 1 "$msg" && exit 1)
+          cfn_signal $exit_code "INFO: Finished running user data for ${AWS::StackName}-database instance"
       Tags:
         - Key: Name
           Value: !Sub ${AppName}-${Stage}
