remove logic for loading Neo4j in public subnet

diff --git a/gfe-db/database/template.yaml b/gfe-db/database/template.yaml
--- a/gfe-db/database/template.yaml
+++ b/gfe-db/database/template.yaml
@@ -165,17 +165,17 @@ Resources:
           [ $(amazon-cloudwatch-agent-ctl -a status | jq -r '.status') = running ] && echo "INFO: CloudWatch Logs Agent is running" || \
             (msg="ERROR: CloudWatch Logs Agent did not initialize correctly" && echo $msg && cfn_signal 1 "$msg" && exit 1)
           # TODO Set NEO4J_URI for private subnet only
-          export USE_PRIVATE_SUBNET=true
-          if [ "$USE_PRIVATE_SUBNET" = true ]; then
-            export NEO4J_URI=bolt://127.0.0.1:7687
-            export NEO4J_ENCRYPTION=false
-          elif [ "$USE_PRIVATE_SUBNET" = false ]; then
-            export NEO4J_URI=neo4j+s://${Subdomain}.${HostDomain}:7687
-            export NEO4J_ENCRYPTION=default
-          else
-            echo "ERROR: USE_PRIVATE_SUBNET must be set to 'true' or 'false'"
-            exit 1
-          fi
+          # export USE_PRIVATE_SUBNET=true
+          # if [ "$USE_PRIVATE_SUBNET" = true ]; then
+          export NEO4J_URI=bolt://127.0.0.1:7687
+          export NEO4J_ENCRYPTION=false
+          # elif [ "$USE_PRIVATE_SUBNET" = false ]; then
+          #   export NEO4J_URI=neo4j+s://${Subdomain}.${HostDomain}:7687
+          #   export NEO4J_ENCRYPTION=default
+          # else
+          #   echo "ERROR: USE_PRIVATE_SUBNET must be set to 'true' or 'false'"
+          #   exit 1
+          # fi
           # Permanently set application environment variables (these should never change for the duration of the deployment)
           echo "INFO: Setting application environment variables"
           echo "INSTANCE_ID=$INSTANCE_ID" > $EC2_USER_HOME/env.sh
@@ -183,7 +183,7 @@ Resources:
           echo "NEO4J_HOME=$NEO4J_HOME" >> $EC2_USER_HOME/env.sh
           echo "STAGE=${Stage}" >> $EC2_USER_HOME/env.sh
           echo "APP_NAME=${AppName}" >> $EC2_USER_HOME/env.sh
-          echo "USE_PRIVATE_SUBNET=$USE_PRIVATE_SUBNET" >> $EC2_USER_HOME/env.sh
+          # echo "USE_PRIVATE_SUBNET=$USE_PRIVATE_SUBNET" >> $EC2_USER_HOME/env.sh
           echo "AWS_REGION=us-east-1" >> $EC2_USER_HOME/env.sh
           echo "DATA_BUCKET_NAME=${DataBucketName}" >> $EC2_USER_HOME/env.sh
           echo "HOST_DOMAIN=${HostDomain}" >> $EC2_USER_HOME/env.sh
@@ -203,14 +203,14 @@ Resources:
           echo "INFO: Validating environment variables"
           exit_code=0
           msg="The following variables failed to be set: "
-          if [ $USE_PRIVATE_SUBNET = "true" ]; then
-            vars="EC2_USER_HOME STAGE APP_NAME USE_PRIVATE_SUBNET AWS_REGION DATA_BUCKET_NAME PRIVATE_IP ADMIN_EMAIL APOC_VERSION GDS_VERSION NEO4J_URI NEO4J_ENCRYPTION"
-          elif [ $USE_PRIVATE_SUBNET = "false" ]; then
-            vars="EC2_USER_HOME STAGE APP_NAME USE_PRIVATE_SUBNET AWS_REGION DATA_BUCKET_NAME HOST_DOMAIN SUBDOMAIN ADMIN_EMAIL APOC_VERSION GDS_VERSION NEO4J_URI NEO4J_ENCRYPTION"
-          else
-            echo "ERROR: USE_PRIVATE_SUBNET must be set to 'true' or 'false'"
-            exit 1
-          fi
+          # if [ $USE_PRIVATE_SUBNET = "true" ]; then
+          vars="EC2_USER_HOME STAGE APP_NAME AWS_REGION DATA_BUCKET_NAME PRIVATE_IP ADMIN_EMAIL APOC_VERSION GDS_VERSION NEO4J_URI NEO4J_ENCRYPTION"
+          # elif [ $USE_PRIVATE_SUBNET = "false" ]; then
+          #   vars="EC2_USER_HOME STAGE APP_NAME USE_PRIVATE_SUBNET AWS_REGION DATA_BUCKET_NAME HOST_DOMAIN SUBDOMAIN ADMIN_EMAIL APOC_VERSION GDS_VERSION NEO4J_URI NEO4J_ENCRYPTION"
+          # else
+          #   echo "ERROR: USE_PRIVATE_SUBNET must be set to 'true' or 'false'"
+          #   exit 1
+          # fi
           for var in $vars; do
               if [ -z "${!var}" ]; then
                   echo "$var is not set"
@@ -220,49 +220,49 @@ Resources:
                   echo "$var is set"
               fi
           done
-          if [ -z "$USE_PRIVATE_SUBNET" ]; then
-            msg="ERROR: USE_PRIVATE_SUBNET must be set"
-            cfn_signal 1 "$msg"
-            exit 1
-          else
-            echo "Found USE_PRIVATE_SUBNET=$USE_PRIVATE_SUBNET"
-          fi
+          # if [ -z "$USE_PRIVATE_SUBNET" ]; then
+          #   msg="ERROR: USE_PRIVATE_SUBNET must be set"
+          #   cfn_signal 1 "$msg"
+          #   exit 1
+          # else
+          #   echo "Found USE_PRIVATE_SUBNET=$USE_PRIVATE_SUBNET"
+          # fi
           install_apoc_plugin() {
             echo "INFO: Installing APOC"
             mv $NEO4J_HOME/labs/apoc-*-core.jar $NEO4J_HOME/plugins
           }
-          # todo test public configuration
-          build_neo4j_public_config() {
-            if [ -z "$SUBDOMAIN" ] || [ -z "$HOST_DOMAIN" ]; then
-              echo "ERROR: SUBDOMAIN and HOST_DOMAIN must be set"
-              exit 1
-            fi
-            sed -i "s/#initial.dbms.default_database=neo4j/initial.dbms.default_database=${!NEO4J_DATABASE_NAME}/g" $NEO4J_HOME/conf/neo4j.conf
-            sed -i 's/#server.default_listen_address=0.0.0.0/server.default_listen_address=0.0.0.0/g' $NEO4J_HOME/conf/neo4j.conf
-            sed -i "s/#server.default_advertised_address=localhost/server.default_advertised_address=$SUBDOMAIN.$HOST_DOMAIN/g" $NEO4J_HOME/conf/neo4j.conf
-            sed -i 's/#server.bolt.tls_level=DISABLED/server.bolt.tls_level=REQUIRED/g' $NEO4J_HOME/conf/neo4j.conf
-            sed -i 's/#server.bolt.listen_address=:7687/server.bolt.listen_address=:7687/g' $NEO4J_HOME/conf/neo4j.conf
-            sed -i 's/#server.bolt.advertised_address=:7687/server.bolt.advertised_address=:7687/g' $NEO4J_HOME/conf/neo4j.conf
-            sed -i 's/server.http.enabled=true/#server.http.enabled=true/g' $NEO4J_HOME/conf/neo4j.conf
-            sed -i 's/server.https.enabled=false/server.https.enabled=true/g' $NEO4J_HOME/conf/neo4j.conf
-            sed -i 's/#server.https.listen_address=:7473/server.https.listen_address=:7473/g' $NEO4J_HOME/conf/neo4j.conf
-            sed -i 's/#server.https.advertised_address=:7473/server.https.advertised_address=:7473/g' $NEO4J_HOME/conf/neo4j.conf
-            sed -i 's/#dbms.ssl.policy.bolt.enabled=true/dbms.ssl.policy.bolt.enabled=true/g' $NEO4J_HOME/conf/neo4j.conf
-            sed -i 's/#dbms.ssl.policy.bolt.base_directory=certificates\/bolt/dbms.ssl.policy.bolt.base_directory=\/opt\/neo4j\/certificates\/bolt/g' $NEO4J_HOME/conf/neo4j.conf
-            sed -i 's/#dbms.ssl.policy.bolt.private_key=private.key/dbms.ssl.policy.bolt.private_key=\/opt\/neo4j\/certificates\/bolt\/neo4j.key/g' $NEO4J_HOME/conf/neo4j.conf
-            sed -i 's/#dbms.ssl.policy.bolt.public_certificate=public.crt/dbms.ssl.policy.bolt.public_certificate=\/opt\/neo4j\/certificates\/bolt\/neo4j.cert/g' $NEO4J_HOME/conf/neo4j.conf
-            sed -i 's/#dbms.ssl.policy.bolt.client_auth=NONE/dbms.ssl.policy.bolt.client_auth=NONE/g' $NEO4J_HOME/conf/neo4j.conf
-            sed -i 's/#dbms.ssl.policy.https.enabled=true/dbms.ssl.policy.https.enabled=true/g' $NEO4J_HOME/conf/neo4j.conf
-            sed -i 's/#dbms.ssl.policy.https.base_directory=certificates\/https/dbms.ssl.policy.https.base_directory=\/opt\/neo4j\/certificates\/https/g' $NEO4J_HOME/conf/neo4j.conf
-            sed -i 's/#dbms.ssl.policy.https.private_key=private.key/dbms.ssl.policy.https.private_key=\/opt\/neo4j\/certificates\/https\/neo4j.key/g' $NEO4J_HOME/conf/neo4j.conf
-            sed -i 's/#dbms.ssl.policy.https.public_certificate=public.crt/dbms.ssl.policy.https.public_certificate=\/opt\/neo4j\/certificates\/https\/neo4j.cert/g' $NEO4J_HOME/conf/neo4j.conf
-            sed -i 's/#dbms.ssl.policy.https.client_auth=NONE/dbms.ssl.policy.https.client_auth=NONE/g' $NEO4J_HOME/conf/neo4j.conf
-            sed -i 's/#dbms.logs.http.enabled=true/dbms.logs.http.enabled=true/g' $NEO4J_HOME/conf/neo4j.conf
-            sed -i 's/#dbms.security.allow_csv_import_from_file_urls=true/dbms.security.allow_csv_import_from_file_urls=true/g' $NEO4J_HOME/conf/neo4j.conf
-            sed -i 's/#dbms.security.procedures.unrestricted=my.extensions.example,my.procedures.*/dbms.security.procedures.unrestricted=apoc.*,gds.*/g' $NEO4J_HOME/conf/neo4j.conf
-            sed -i 's/#dbms.security.procedures.allowlist=apoc.coll.*,apoc.load.*,gds.*/dbms.security.procedures.allowlist=apoc.*,gds.*/g' $NEO4J_HOME/conf/neo4j.conf
-            $NEO4J_HOME/bin/neo4j-admin server memory-recommendation | grep -v ^# >> $NEO4J_HOME/conf/neo4j.conf
-          }
+          # # todo test public configuration
+          # build_neo4j_public_config() {
+          #   if [ -z "$SUBDOMAIN" ] || [ -z "$HOST_DOMAIN" ]; then
+          #     echo "ERROR: SUBDOMAIN and HOST_DOMAIN must be set"
+          #     exit 1
+          #   fi
+          #   sed -i "s/#initial.dbms.default_database=neo4j/initial.dbms.default_database=${!NEO4J_DATABASE_NAME}/g" $NEO4J_HOME/conf/neo4j.conf
+          #   sed -i 's/#server.default_listen_address=0.0.0.0/server.default_listen_address=0.0.0.0/g' $NEO4J_HOME/conf/neo4j.conf
+          #   sed -i "s/#server.default_advertised_address=localhost/server.default_advertised_address=$SUBDOMAIN.$HOST_DOMAIN/g" $NEO4J_HOME/conf/neo4j.conf
+          #   sed -i 's/#server.bolt.tls_level=DISABLED/server.bolt.tls_level=REQUIRED/g' $NEO4J_HOME/conf/neo4j.conf
+          #   sed -i 's/#server.bolt.listen_address=:7687/server.bolt.listen_address=:7687/g' $NEO4J_HOME/conf/neo4j.conf
+          #   sed -i 's/#server.bolt.advertised_address=:7687/server.bolt.advertised_address=:7687/g' $NEO4J_HOME/conf/neo4j.conf
+          #   sed -i 's/server.http.enabled=true/#server.http.enabled=true/g' $NEO4J_HOME/conf/neo4j.conf
+          #   sed -i 's/server.https.enabled=false/server.https.enabled=true/g' $NEO4J_HOME/conf/neo4j.conf
+          #   sed -i 's/#server.https.listen_address=:7473/server.https.listen_address=:7473/g' $NEO4J_HOME/conf/neo4j.conf
+          #   sed -i 's/#server.https.advertised_address=:7473/server.https.advertised_address=:7473/g' $NEO4J_HOME/conf/neo4j.conf
+          #   sed -i 's/#dbms.ssl.policy.bolt.enabled=true/dbms.ssl.policy.bolt.enabled=true/g' $NEO4J_HOME/conf/neo4j.conf
+          #   sed -i 's/#dbms.ssl.policy.bolt.base_directory=certificates\/bolt/dbms.ssl.policy.bolt.base_directory=\/opt\/neo4j\/certificates\/bolt/g' $NEO4J_HOME/conf/neo4j.conf
+          #   sed -i 's/#dbms.ssl.policy.bolt.private_key=private.key/dbms.ssl.policy.bolt.private_key=\/opt\/neo4j\/certificates\/bolt\/neo4j.key/g' $NEO4J_HOME/conf/neo4j.conf
+          #   sed -i 's/#dbms.ssl.policy.bolt.public_certificate=public.crt/dbms.ssl.policy.bolt.public_certificate=\/opt\/neo4j\/certificates\/bolt\/neo4j.cert/g' $NEO4J_HOME/conf/neo4j.conf
+          #   sed -i 's/#dbms.ssl.policy.bolt.client_auth=NONE/dbms.ssl.policy.bolt.client_auth=NONE/g' $NEO4J_HOME/conf/neo4j.conf
+          #   sed -i 's/#dbms.ssl.policy.https.enabled=true/dbms.ssl.policy.https.enabled=true/g' $NEO4J_HOME/conf/neo4j.conf
+          #   sed -i 's/#dbms.ssl.policy.https.base_directory=certificates\/https/dbms.ssl.policy.https.base_directory=\/opt\/neo4j\/certificates\/https/g' $NEO4J_HOME/conf/neo4j.conf
+          #   sed -i 's/#dbms.ssl.policy.https.private_key=private.key/dbms.ssl.policy.https.private_key=\/opt\/neo4j\/certificates\/https\/neo4j.key/g' $NEO4J_HOME/conf/neo4j.conf
+          #   sed -i 's/#dbms.ssl.policy.https.public_certificate=public.crt/dbms.ssl.policy.https.public_certificate=\/opt\/neo4j\/certificates\/https\/neo4j.cert/g' $NEO4J_HOME/conf/neo4j.conf
+          #   sed -i 's/#dbms.ssl.policy.https.client_auth=NONE/dbms.ssl.policy.https.client_auth=NONE/g' $NEO4J_HOME/conf/neo4j.conf
+          #   sed -i 's/#dbms.logs.http.enabled=true/dbms.logs.http.enabled=true/g' $NEO4J_HOME/conf/neo4j.conf
+          #   sed -i 's/#dbms.security.allow_csv_import_from_file_urls=true/dbms.security.allow_csv_import_from_file_urls=true/g' $NEO4J_HOME/conf/neo4j.conf
+          #   sed -i 's/#dbms.security.procedures.unrestricted=my.extensions.example,my.procedures.*/dbms.security.procedures.unrestricted=apoc.*,gds.*/g' $NEO4J_HOME/conf/neo4j.conf
+          #   sed -i 's/#dbms.security.procedures.allowlist=apoc.coll.*,apoc.load.*,gds.*/dbms.security.procedures.allowlist=apoc.*,gds.*/g' $NEO4J_HOME/conf/neo4j.conf
+          #   $NEO4J_HOME/bin/neo4j-admin server memory-recommendation | grep -v ^# >> $NEO4J_HOME/conf/neo4j.conf
+          # }
           build_neo4j_private_config() {
             sed -i "s/#initial.dbms.default_database=neo4j/initial.dbms.default_database=${!NEO4J_DATABASE_NAME}/g" $NEO4J_HOME/conf/neo4j.conf
             sed -i 's/#server.default_listen_address=0.0.0.0/server.default_listen_address=0.0.0.0/g' $NEO4J_HOME/conf/neo4j.conf
@@ -315,16 +315,16 @@ Resources:
             echo "INFO: Neo4j systemd service file has been created at $SERVICE_FILE"
             install_apoc_plugin
             cp $NEO4J_HOME/conf/neo4j.conf $NEO4J_HOME/conf/neo4j.conf.bak
-            if [ "$USE_PRIVATE_SUBNET" = "false" ]; then
-              echo "INFO: Building public subnet configuration for Neo4j"
-              build_neo4j_public_config;
-            elif [ "$USE_PRIVATE_SUBNET" = "true" ]; then
-              echo "INFO: Building private subnet configuration for Neo4j"
-              build_neo4j_private_config;
-            else
-              echo "ERROR: USE_PRIVATE_SUBNET must be set to 'true' or 'false'"
-              exit 1
-            fi
+            # if [ "$USE_PRIVATE_SUBNET" = "false" ]; then
+            #   echo "INFO: Building public subnet configuration for Neo4j"
+            #   build_neo4j_public_config;
+            # elif [ "$USE_PRIVATE_SUBNET" = "true" ]; then
+            echo "INFO: Building private subnet configuration for Neo4j"
+            build_neo4j_private_config;
+            # else
+            #   echo "ERROR: USE_PRIVATE_SUBNET must be set to 'true' or 'false'"
+            #   exit 1
+            # fi
             systemctl daemon-reload
             systemctl enable neo4j
             systemctl start neo4j
