deploy vpc with private instance

diff --git a/gfe-db/infrastructure/Makefile b/gfe-db/infrastructure/Makefile
--- a/gfe-db/infrastructure/Makefile
+++ b/gfe-db/infrastructure/Makefile
@@ -76,20 +76,31 @@ service.deploy.update-dns:
 	echo && \
 	echo "Successfully updated DNS records"
 
+# TODO for CREATE_VPC=true and USE_PRIVATE_SUBNET=true, need to get the PrivateSubnetId from SSM Param Store, the endpoints are created
+# but they are not associated with any subnet
 service.deploy.create-endpoint: #=> service=<string>
-	@neo4j_sg_id=$$(aws ssm get-parameters \
-		--names "/${APP_NAME}/${STAGE}/${AWS_REGION}/Neo4jDatabaseSecurityGroupId" \
-        --output json | jq -r '.Parameters[0].Value') && \
-	vpc_id=$$(aws ssm get-parameters \
-		--names "/${APP_NAME}/${STAGE}/${AWS_REGION}/VpcId" \
-		--output json | jq -r '.Parameters[0].Value') && \
-	if [ "$$neo4j_sg_id" = "" ]; then \
-		echo "\033[0;31mERROR: Neo4j security group id not found\033[0m" && exit 1; \
-	fi && \
-	if [ -z $$service ]; then \
+	@if [ -z $$service ]; then \
 		echo "\033[0;31mERROR: No service specified\033[0m" && exit 1; \
 	elif [ $$service != "ssm" ] && [ $$service != "secretsmanager" ] && [ $$service != "s3" ]; then \
 		echo "\033[0;31mERROR: Invalid service specified. Valid services are 'ssm', 'secretsmanager' or 's3'\033[0m" && exit 1; \
+	fi && \
+	vpc_id=$$(aws ssm get-parameters \
+		--names "/${APP_NAME}/${STAGE}/${AWS_REGION}/VpcId" \
+		--output json | jq -r '.Parameters[0].Value') && \
+	if [ "$$vpc_id" = "" ]; then \
+		echo "\033[0;31mERROR: VPC ID not found\033[0m" && exit 1; \
+	fi && \
+	neo4j_sg_id=$$(aws ssm get-parameters \
+		--names "/${APP_NAME}/${STAGE}/${AWS_REGION}/Neo4jDatabaseSecurityGroupId" \
+        --output json | jq -r '.Parameters[0].Value') && \
+	if [ "$$neo4j_sg_id" = "" ]; then \
+		echo "\033[0;31mERROR: Neo4j security group id not found\033[0m" && exit 1; \
+	fi && \
+	private_subnet_id=$$(aws ssm get-parameters \
+		--names "/${APP_NAME}/${STAGE}/${AWS_REGION}/PrivateSubnetId" \
+		--output json | jq -r '.Parameters[0].Value') && \
+	if [ "$$private_subnet_id" = "" ]; then \
+		echo "\033[0;31mERROR: Private subnet id not found\033[0m" && exit 1; \
 	fi && \
 	if [ $$service = "ssm" ] && [ ${CREATE_SSM_VPC_ENDPOINT} != "true" ]; then \
 		echo "\033[0;31mERROR: \`CREATE_SSM_VPC_ENDPOINT\` must be set to \`true\` to create a Systems Manager VPC endpoint\033[0m" && exit 1; \
@@ -103,7 +114,7 @@ service.deploy.create-endpoint: #=> service=<string>
 	res=$$(aws ec2 create-vpc-endpoint \
 		--vpc-id $$vpc_id \
 		--service-name com.amazonaws.$${AWS_REGION}.$$service \
-		--subnet-ids $${PRIVATE_SUBNET_ID} \
+		--subnet-ids $$private_subnet_id \
 		--security-group-ids $$neo4j_sg_id \
 		--vpc-endpoint-type Interface \
 		--tag-specifications "ResourceType=vpc-endpoint,Tags=[{Key=Name,Value=$${STAGE}-$${APP_NAME}-$${service}-vpce}]") && \
@@ -117,7 +128,7 @@ service.deploy.create-endpoint: #=> service=<string>
 	echo $$res | jq -r
 	$(call blue, Successfully created VPC endpoint for $$service)
 
-# test the return code of aws cloudformation deploy and exit if it is 1
+# TODO test the return code of aws cloudformation deploy and exit if it is 1
 service.deploy:
 	@echo "$$(gdate -u +'%Y-%m-%d %H:%M:%S.%3N') - Deploying CloudFormation" 2>&1 | tee -a $${CFN_LOG_PATH}
 	@aws cloudformation deploy \
