create and delete endpoints using AWS CLI instead of CloudFormation

diff --git a/gfe-db/infrastructure/Makefile b/gfe-db/infrastructure/Makefile
--- a/gfe-db/infrastructure/Makefile
+++ b/gfe-db/infrastructure/Makefile
@@ -1,11 +1,38 @@
 .PHONY: service.update-vpc-endpoints
 SERVICE := infrastructure
 
+# stdout colors
+# blue: runtime message, no action required
+# green: parameter value message, no action required
+# yellow: message to user, action required
+# red: error message, action required
+define blue
+	@tput setaf 4
+	@echo $1
+	@tput sgr0
+endef
+
+define green
+	@tput setaf 2
+	@echo $1
+	@tput sgr0
+endef
+
+define yellow
+	@tput setaf 3
+	@echo $1
+	@tput sgr0
+endef
+
+define red
+	@tput setaf 1
+	@echo $1
+	@tput sgr0
+endef
+
 target:
 	$(info ${HELP_MESSAGE})
 	@exit 0
-
-# service.env.validate:
 
 deploy: 
 	@echo "$$(gdate -u +'%Y-%m-%d %H:%M:%S.%3N') - Deploying ${SERVICE} service" 2>&1 | tee -a $${CFN_LOG_PATH}
@@ -14,6 +41,16 @@ ifeq ($(USE_PRIVATE_SUBNET),false)
 	$(MAKE) service.deploy.update-dns
 endif
 	$(MAKE) service.monitoring.create-subscriptions
+ifeq ($(HAS_STAGE),null)
+ifeq ($(CREATE_SSM_VPC_ENDPOINT),true)
+	$(call blue, Creating Systems Manager VPC endpoint..)
+	$(MAKE) service.deploy.create-endpoint service=ssm
+endif
+ifeq ($(CREATE_SECRETSMANAGER_VPC_ENDPOINT),true)
+	$(call blue, Creating SecretsManager VPC endpoint...)
+	$(MAKE) service.deploy.create-endpoint service=secretsmanager
+endif
+endif
 
 # TODO add waiter: aws route53 wait resource-record-sets-changed --id <value>
 service.deploy.update-dns:
@@ -34,6 +71,33 @@ service.deploy.update-dns:
 	aws route53 wait resource-record-sets-changed --id $$(echo $$res | jq -r '.ChangeInfo.Id') && \
 	echo && \
 	echo "Successfully updated DNS records"
+
+service.deploy.create-endpoint: #=> service=<string>
+	@neo4j_sg_id=$$(aws ssm get-parameters \
+		--names "/${APP_NAME}/${STAGE}/${AWS_REGION}/Neo4jDatabaseSecurityGroupId" \
+        --output json | jq -r '.Parameters[0].Value') && \
+	if [ "$$neo4j_sg_id" = "" ]; then \
+		echo "Neo4j security group id not found" && exit 1; \
+	fi && \
+	if [ -z $$service ]; then \
+		echo "No service specified" && exit 1; \
+	elif [ $$service != "ssm" ] && [ $$service != "secretsmanager" ]; then \
+		echo "Invalid service specified. Valid services are 'ssm', 'secretsmanager'" && exit 1; \
+	fi && \
+	res=$$(aws ec2 create-vpc-endpoint \
+		--vpc-id $${VPC_ID} \
+		--service-name com.amazonaws.$${AWS_REGION}.$$service \
+		--security-group-ids $$neo4j_sg_id \
+		--vpc-endpoint-type Interface) \
+		--tag-specification "ResourceType=vpc-endpoint,Tags=[{Key=Name,Value=$${STAGE}-$${APP_NAME}-$${service}-vpce}]" && \
+	vpc_endpoint_id=$$(echo $$res | jq -r '.VpcEndpoint.VpcEndpointId') && \
+	echo "Saving endpoint id to SSM Parameter Store" && \
+	aws ssm put-parameter \
+		--name "/${APP_NAME}/${STAGE}/${AWS_REGION}/$${service}EndpointId" \
+		--value "$$vpc_endpoint_id" \
+		--type String \
+		--overwrite
+	$(call blue, Successfully created VPC endpoint for $$service)
 
 # TODO add cloudformation waiter for stack create complete and exit if failed
 # TODO test AWSCLI output and validate the stack was created successfully
@@ -151,11 +215,34 @@ service.monitoring.subscribe-email: #email=<string>
 delete: ##=> Delete resources
 	@echo "$$(gdate -u +'%Y-%m-%d %H:%M:%S.%3N') - Deleting ${SERVICE} service" 2>&1 | tee -a $${CFN_LOG_PATH}
 ifeq ($(data),true)
-	@echo "$$(gdate -u +'%Y-%m-%d %H:%M:%S.%3N') - Deleting data in $$DATA_BUCKET_NAME" 2>&1 | tee -a $${CFN_LOG_PATH}
+	@echo "$$(gdate -u +'%Y-%m-%d %H:%M:%S.%3N') - Deleting data in $${DATA_BUCKET_NAME}" 2>&1 | tee -a $${CFN_LOG_PATH}
 	@aws s3 rm --recursive s3://$${DATA_BUCKET_NAME}/
 endif
 	# $(MAKE) service.remove-security-groups
+ifeq ($(CREATE_SSM_VPC_ENDPOINT),true)
+	$(MAKE) service.delete.delete-endpoint service=ssm
+endif
+ifeq ($(CREATE_SECRETSMANAGER_VPC_ENDPOINT),true)
+	$(MAKE) service.delete.delete-endpoint service=secretsmanager
+endif	
 	$(MAKE) service.delete
+
+# TODO get parameter "/$${APP_NAME}/$${STAGE}/$${AWS_REGION}/$${service}EndpointId" from SSM
+service.delete.delete-endpoint: #=> service=<string>
+	@	if [ -z $$service ]; then \
+		echo "No service specified" && exit 1; \
+	elif [ $$service != "ssm" ] && [ $$service != "secretsmanager" ]; then \
+		echo "Invalid service specified. Valid services are 'ssm', 'secretsmanager'" && exit 1; \
+	fi
+	@endpoint_id=$$(aws ssm get-parameters \
+		--names "/${APP_NAME}/${STAGE}/${AWS_REGION}/$${service}EndpointId" \
+		--with-decryption \
+		--query "Parameters[0].Value" \
+		--output text) && \
+	echo "Deleting VPC endpoint for $${service}..." && \
+	res=$$(aws ec2 delete-vpc-endpoints \
+		--vpc-endpoint-ids "$$endpoint_id") && \
+	echo $$res | jq -r
 
 service.delete:
 	@echo "$$(gdate -u +'%Y-%m-%d %H:%M:%S.%3N') - Deleting CloudFormation" 2>&1 | tee -a $${CFN_LOG_PATH}
