add and remove security groups on VPC endpoints

diff --git a/gfe-db/infrastructure/Makefile b/gfe-db/infrastructure/Makefile
--- a/gfe-db/infrastructure/Makefile
+++ b/gfe-db/infrastructure/Makefile
@@ -62,22 +62,56 @@ ifeq ($(CREATE_SECRETSMANAGER_ENDPOINT),false)
 	$(MAKE) service.update-vpc-endpoint service=secretsmanager
 endif
 
+# TODO get endpoint id from env vars, --filter "Name=subnet-id,Values=$${PRIVATE_SUBNET_ID}" does not work
+# the vpc endpoint must match PRIVATE_SUBNET_ID env var
 service.update-vpc-endpoint: #service=<string[ssm,secretsmanager]>
-	@echo "$$(gdate -u +'%Y-%m-%d %H:%M:%S.%3N') - Updating $${service} VPC endpoint security group" 2>&1 | tee -a $${CFN_LOG_PATH}
-	@endpoint_id=$$(aws ec2 describe-vpc-endpoints \
-		--filters "Name=service-name,Values=com.amazonaws.$${AWS_REGION}.$$service" \
-		--query "VpcEndpoints[0].VpcEndpointId" \
-		--output text) && \
-	echo "Endpoint ID: $$endpoint_id" && \
+	@echo "\033[0;32m$$(gdate -u +'%Y-%m-%d %H:%M:%S.%3N') - Adding security group to $${service} VPC endpoint\033[0m" 2>&1 | tee -a $${CFN_LOG_PATH}
+	@endpoint_json=$$(aws ec2 describe-vpc-endpoints | jq 'del(.VpcEndpoints[].PolicyDocument)') && \
+	endpoint_id=$$(echo $$endpoint_json | jq -r --arg subnet "$${PRIVATE_SUBNET_ID}" '.VpcEndpoints[] | select(.SubnetIds[] == $$subnet) .VpcEndpointId') && \
+	if [ -z "$$endpoint_id" ]; then \
+		echo "$${service} VPC endpoint is not associated with \`PRIVATE_SUBNET_ID\` ($${PRIVATE_SUBNET_ID})" && exit 1; \
+	fi; \
+	[ "$${service}" = "ssm" ] && endpoint_id=$$SSM_ENDPOINT_ID; \
+	[ "$${service}" = "secretsmanager" ] && endpoint_id=$$SECRETSMANAGER_ENDPOINT_ID; \
+	echo "\033[0;34mFound VPC endpoint ID: $$endpoint_id" && \
 	security_group_id=$$(aws ssm get-parameters \
 		--names "/$${APP_NAME}/$${STAGE}/$${AWS_REGION}/Neo4jDatabaseSecurityGroupId" \
 		--with-decryption \
 		--query "Parameters[0].Value" \
 		--output text) && \
-	echo "Security Group ID: $$security_group_id" && \
-	aws ec2 modify-vpc-endpoint \
+	echo "Found security group ID: $$security_group_id" && \
+	response=$$(aws ec2 modify-vpc-endpoint \
 		--vpc-endpoint-id "$$endpoint_id" \
-		--add-security-group-ids "$$security_group_id" | jq -r
+		--add-security-group-ids "$$security_group_id" | jq -r '.Return') && \
+	[ "$$response" = "true" ] && echo "\033[0;32mSuccessfully added security group to $${service} VPC endpoint\033[0m" || \
+	(echo "\033[0;31mFailed to add security group to $${service} VPC endpoint\033[0m" && exit 1)
+
+service.remove-security-groups:
+ifeq ($(CREATE_SSM_ENDPOINT),false)
+	$(MAKE) service.remove-security-group service=ssm
+endif
+ifeq ($(CREATE_SECRETSMANAGER_ENDPOINT),false)
+	$(MAKE) service.remove-security-group service=secretsmanager
+endif
+
+# Removes the Neo4j security group from the VPC endpoints
+# aws ec2 modify-vpc-endpoint --remove-security-group-ids 
+service.remove-security-group: #service=<string[ssm,secretsmanager]>
+	@echo "\033[0;32m$$(gdate -u +'%Y-%m-%d %H:%M:%S.%3N') - Removing security group from $${service} VPC endpoint\033[0m" 2>&1 | tee -a $${CFN_LOG_PATH}
+	@[ "$${service}" = "ssm" ] && endpoint_id=$$SSM_ENDPOINT_ID; \
+	[ "$${service}" = "secretsmanager" ] && endpoint_id=$$SECRETSMANAGER_ENDPOINT_ID; \
+	echo "\033[0;34mFound VPC endpoint ID: $$endpoint_id" && \
+	security_group_id=$$(aws ssm get-parameters \
+		--names "/$${APP_NAME}/$${STAGE}/$${AWS_REGION}/Neo4jDatabaseSecurityGroupId" \
+		--with-decryption \
+		--query "Parameters[0].Value" \
+		--output text) && \
+	echo "Found security group ID: $$security_group_id" && \
+	response=$$(aws ec2 modify-vpc-endpoint \
+		--vpc-endpoint-id "$$endpoint_id" \
+		--remove-security-group-ids "$$security_group_id" | jq -r '.Return') && \
+	[ "$$response" = "true" ] && echo "\033[0;32mSuccessfully removed security group from $${service} VPC endpoint\033[0m" || \
+	(echo "\033[0;31mFailed to remove security group from $${service} VPC endpoint\033[0m" && exit 1) | jq -r
 
 service.monitoring.create-subscriptions:
 	@echo "$$(gdate -u +'%Y-%m-%d %H:%M:%S.%3N') - Creating SNS topic subscriptions" 2>&1 | tee -a $${CFN_LOG_PATH}
@@ -105,12 +139,14 @@ service.monitoring.subscribe-email: #email=<string>
 		--protocol email \
 		--notification-endpoint "$$email" 2>&1 | tee -a $${CFN_LOG_PATH} || true;
 
+# TODO remove the sg association from the vpc endpoints before deleting
 delete: ##=> Delete resources
 	@echo "$$(gdate -u +'%Y-%m-%d %H:%M:%S.%3N') - Deleting ${SERVICE} service" 2>&1 | tee -a $${CFN_LOG_PATH}
 ifeq ($(data),true)
 	@echo "$$(gdate -u +'%Y-%m-%d %H:%M:%S.%3N') - Deleting data in $$DATA_BUCKET_NAME" 2>&1 | tee -a $${CFN_LOG_PATH}
 	@aws s3 rm --recursive s3://$${DATA_BUCKET_NAME}/
 endif
+	$(MAKE) service.remove-security-groups
 	$(MAKE) service.delete
 
 service.delete:
