deploy and delete Elastic IP, NAT Gateway and params

diff --git a/gfe-db/infrastructure/Makefile b/gfe-db/infrastructure/Makefile
--- a/gfe-db/infrastructure/Makefile
+++ b/gfe-db/infrastructure/Makefile
@@ -148,6 +148,80 @@ service.deploy:
 			PrivateSubnetId="$${PRIVATE_SUBNET_ID}" \
 			GitHubPersonalAccessToken="$$GITHUB_PERSONAL_ACCESS_TOKEN"
 
+service.nat-gateway.eip.create:
+	@eip=$$(aws ssm get-parameters \
+		--names "/${APP_NAME}/${STAGE}/${AWS_REGION}/NatGatewayElasticIp" \
+		--output json | jq -r '.Parameters[0].Value') && \
+	if [ "$$eip" = "null" ]; then \
+		res=$$(aws ec2 allocate-address \
+			--domain vpc \
+			--tag-specifications "ResourceType=elastic-ip,Tags=[{Key=Name,Value=$${STAGE}-$${APP_NAME}-nat-gateway-eip}]" \
+			) && \
+		echo $$res | jq -r 2>&1 | tee -a $${CFN_LOG_PATH} && \
+		eip=$$(echo $$res | jq -r '.PublicIp') && \
+		echo "\033[0;34mSaving Elastic IP to SSM Parameter Store\033[0m" && \
+		res=$$(aws ssm put-parameter \
+			--name "/${APP_NAME}/${STAGE}/${AWS_REGION}/NatGatewayElasticIp" \
+			--value "$$eip" \
+			--type String \
+			--overwrite) && \
+		echo $$res | jq -r; \
+	else \
+		echo "\033[0;34mFound existing Elastic IP: $$eip\033[0m"; \
+	fi
+
+# wait for NAT Gateway to be created
+service.nat-gateway.resource.create:
+	@echo "$$(gdate -u +'%Y-%m-%d %H:%M:%S.%3N') - Creating NAT Gateway" 2>&1 | tee -a $${CFN_LOG_PATH}
+	@nat_gateway_id=$$(aws ssm get-parameters \
+		--names "/${APP_NAME}/${STAGE}/${AWS_REGION}/NatGatewayId" \
+		--output json | jq -r '.Parameters[0].Value') && \
+	if [ "$$nat_gateway_id" = "null" ]; then \
+		eip=$$(aws ssm get-parameters \
+			--names "/${APP_NAME}/${STAGE}/${AWS_REGION}/NatGatewayElasticIp" \
+			--output json | jq -r '.Parameters[0].Value') && \
+		if [ "$$eip" = "" ]; then \
+			echo "\033[0;31mERROR: Elastic IP not found\033[0m" && exit 1; \
+		else \
+			allocation_id=$$(aws ec2 describe-addresses \
+				--public-ips "$$eip" \
+				--query "Addresses[0].AllocationId" \
+				--output text) && \
+			if [ "$$allocation_id" = "" ]; then \
+				echo "\033[0;31mERROR: Allocation ID not found\033[0m" && exit 1; \
+			fi; \
+		fi && \
+		public_subnet_id=$$(aws ssm get-parameters \
+			--names "/${APP_NAME}/${STAGE}/${AWS_REGION}/PublicSubnetId" \
+			--output json | jq -r '.Parameters[0].Value') && \
+		if [ "$$public_subnet_id" = "null" ]; then \
+			echo "\033[0;31mERROR: Public subnet id not found\033[0m" && exit 1; \
+		fi && \
+		echo "$$(gdate -u +'%Y-%m-%d %H:%M:%S.%3N') - Deploying NAT Gateway" 2>&1 | tee -a $${CFN_LOG_PATH} && \
+		res=$$(aws ec2 create-nat-gateway \
+			--allocation-id "$$allocation_id" \
+			--subnet-id "$$public_subnet_id" \
+			--tag-specifications "ResourceType=natgateway,Tags=[{Key=Name,Value=$${STAGE}-$${APP_NAME}-nat-gateway}]") && \
+		echo $$res | jq -r 2>&1 | tee -a $${CFN_LOG_PATH} && \
+		nat_gateway_id=$$(echo $$res | jq -r '.NatGateway.NatGatewayId') && \
+		res=$$(aws ec2 wait nat-gateway-available \
+			--nat-gateway-ids "$$nat_gateway_id") && \
+		echo "\033[0;34mSaving NAT Gateway ID to SSM Parameter Store\033[0m" && \
+		res=$$(aws ssm put-parameter \
+			--name "/${APP_NAME}/${STAGE}/${AWS_REGION}/NatGatewayId" \
+			--value "$$nat_gateway_id" \
+			--type String \
+			--overwrite) && \
+		echo $$res | jq -r; \
+	else \
+		echo "\033[0;34mFound existing NAT Gateway: $$nat_gateway_id\033[0m"; \
+	fi
+
+service.nat-gateway.deploy:
+	$(MAKE) service.nat-gateway.eip.create
+	$(MAKE) service.nat-gateway.resource.create
+
+
 service.monitoring.create-subscriptions:
 	@echo "$$(gdate -u +'%Y-%m-%d %H:%M:%S.%3N') - Creating SNS topic subscriptions" 2>&1 | tee -a $${CFN_LOG_PATH}
 	@topic_arn=$$(aws ssm get-parameters \
@@ -216,6 +290,61 @@ service.delete:
 		--stack-name "$${STAGE}-$${APP_NAME}-${SERVICE}" 2>&1 | tee -a $${CFN_LOG_PATH} || true && \
 	aws cloudformation wait stack-delete-complete \
 		--stack-name "$${STAGE}-$${APP_NAME}-${SERVICE}" 2>&1 | tee -a $${CFN_LOG_PATH} || true
+
+service.nat-gateway.eip.delete:
+	@echo "$$(gdate -u +'%Y-%m-%d %H:%M:%S.%3N') - Deleting NAT Gateway Elastic IP" 2>&1 | tee -a $${CFN_LOG_PATH}
+	@eip=$$(aws ssm get-parameters \
+		--names "/${APP_NAME}/${STAGE}/${AWS_REGION}/NatGatewayElasticIp" \
+		--output json | jq -r '.Parameters[0].Value') && \
+	if [ "$$eip" != "null" ]; then \
+		echo "\033[0;34mFound existing Elastic IP: $$eip\033[0m" && \
+		allocation_id=$$(aws ec2 describe-addresses \
+			--public-ips "$$eip" \
+			--query "Addresses[0].AllocationId" \
+			--output text) && \
+		if [ "$$allocation_id" != "null" ]; then \
+			res=$$(aws ec2 release-address \
+				--allocation-id "$$allocation_id") && \
+			echo $$res | jq -r 2>&1 | tee -a $${CFN_LOG_PATH} || true; \
+		fi; \
+		res=$$(aws ssm delete-parameter \
+			--name "/${APP_NAME}/${STAGE}/${AWS_REGION}/NatGatewayElasticIp") && \
+		echo $$res | jq -r && \
+		echo "\033[0;34mSuccessfully deleted Elastic IP\033[0m"; \
+	else \
+		echo "\033[0;33mNo Elastic IP found\033[0m" && \
+		exit 0; \
+	fi
+
+# wait for the NAT Gateway to be deleted before deleting the Elastic IP
+service.nat-gateway.resource.delete:
+	@echo "$$(gdate -u +'%Y-%m-%d %H:%M:%S.%3N') - Deleting NAT Gateway" 2>&1 | tee -a $${CFN_LOG_PATH}
+	@nat_gateway_id=$$(aws ssm get-parameters \
+		--names "/${APP_NAME}/${STAGE}/${AWS_REGION}/NatGatewayId" \
+		--output json | jq -r '.Parameters[0].Value') && \
+		echo "$$nat_gateway_id" && \
+	if [ "$$nat_gateway_id" != "null" ]; then \
+		echo "\033[0;34mFound existing NAT Gateway: $$nat_gateway_id\033[0m" && \
+		res=$$(aws ec2 delete-nat-gateway \
+			--nat-gateway-id "$$nat_gateway_id") && \
+		echo $$res | jq -r 2>&1 | tee -a $${CFN_LOG_PATH} || true; \
+	else \
+		echo "\033[0;33mNo NAT Gateway found\033[0m" && \
+		exit 0; \
+	fi && \
+	echo "\033[0;34mWaiting for NAT Gateway to be deleted...\033[0m" && \
+	res=$$(aws ec2 wait nat-gateway-deleted \
+		--nat-gateway-ids "$$nat_gateway_id") && \
+	echo $$res | jq -r 2>&1 | tee -a $${CFN_LOG_PATH} && \
+	echo "\033[0;34mDeleting NAT Gateway ID from SSM Parameter Store\033[0m" && \
+	res=$$(aws ssm delete-parameter \
+		--name "/${APP_NAME}/${STAGE}/${AWS_REGION}/NatGatewayId") && \
+	echo $$res | jq -r && \
+	echo "\033[0;34mSuccessfully deleted NAT Gateway\033[0m"
+
+service.nat-gateway.delete:
+	$(MAKE) service.nat-gateway.resource.delete
+	$(MAKE) service.nat-gateway.eip.delete
 
 service.parameters.delete:
 	@echo "$$(gdate -u +'%Y-%m-%d %H:%M:%S.%3N') - Deleting SSM parameters" 2>&1 | tee -a ${CFN_LOG_PATH}
